SET IDENTITY_INSERT [dbo].[Team] ON
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (1, N'Arizona Cardinals', N'1', N'Phoenix', N'AR')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (2, N'Atlanta Falcons', N'1', N't', N'a')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (3, N'Houston Texans', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (4, N'Baltimore Ravens', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (5, N'Chicago Bears', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (6, N'Cincinnati Bengals', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (7, N'Minnesota Vikings', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (8, N'Philadelphia Eagles', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (9, N'San Diego Chargers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (10, N'San Francisco 49ers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (11, N'Buffalo Bills', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (12, N'Dallas Cowboys', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (13, N'Denver Broncos', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (14, N'Green Bay Packers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (15, N'New England Patriots', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (16, N'New York Giants', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (17, N'New York Jets', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (18, N'Seattle Seahawks', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (19, N'St. Louis Rams', N'', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (20, N'Washington Redskins', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (21, N'Indianapolis Colts', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (22, N'Pittsburgh Steelers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (23, N'Carolina Panthers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (24, N'Detroit Lions', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (25, N'Jacksonville Jaguars', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (26, N'Kansas City Chiefs', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (27, N'Miami Dolphins', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (28, N'Oakland Raiders', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (29, N'Tampa Bay Buccaneers', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (30, N'Tennessee Titans', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (31, N'Cleveland Browns', N'1', N'1', N'1')
INSERT [dbo].[Team] ([Id], [Name], [TimeZone], [City], [StateId]) VALUES (32, N'New Orleans Saints', N'1', N'1', N'1')
SET IDENTITY_INSERT [dbo].[Team] OFF